### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by marc726** [marc726/beam#2]
- [ ] Implement a ETA, Speed, and Progress bar. 
- [ ] Edge Cases for enabling and disabling buttons
- [ ] UDP or TCP
- [ ] Automate the port selection/Get rid of the port forwarding dependency.
